### ISSUE TITLE
ERROR - IndexError: tuple index out of range

### ISSUE THREAD

**Issue by ghost** [michaelimfeld/ownbot#11]
Whenever I run `/start` or one of the admin commands, I get the following error.

```
2019-06-24 09:25:02,591 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "C:\Users\benbridges\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\dispatcher.py", line 333, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\benbridges\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\conversationhandler.py", line 326, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "C:\Users\benbridges\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "C:\Users\benbridges\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ownbot\auth.py", line 80, in call
    update = args[1 + offset]
IndexError: tuple index out of range
```

I'm not sure what I'm doing wrong or if it's caused by the fact I'm running on windows or beta 12.0.0b1 of python-telegram-bot

Complete code here: https://pastebin.com/76pEHnBZ

**Comment by jon4hz** [comment]
Hi, pastebin link is no more available but the error is probably because you use the bot with the use_context function. Ownbot can't handle that.
